trigger:
- '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'  # You can choose a different VM image if needed

stages:
- stage: StartAndStopLoop
  jobs:
  - job: LoopJob
    steps:
    - script: |
        echo "Logging in to Azure Container Registry"
        az acr login --name sermadregistry --username sermadregistry --password jhXrqsXe7dBJ4tximYxeC9I2TF6gxcCxnirmS5xWf/+ACRDgPZMD

        for i in {1..3}  # Loop 3 times (change the number as needed)
        do
          # Use Azure CLI to start the Azure Container Instance
          az container start --name dbt-core-container --resource-group harpoon
          
          # Add a delay between start and stop if needed
          sleep 60  # Sleep for 60 seconds (adjust as needed)
          
          # Use Azure CLI to stop the Azure Container Instance
          az container stop --name dbt-core-container --resource-group harpoon
        done
      displayName: 'Loop: Start and Stop Container'
