{% snapshot servicenow_actual_facilities_request_stg %}
    {{
        config(
          target_schema='staging',
          strategy='check',
          unique_key='sys_id_value',
          check_cols=['parent_value','sla_suspended_reason_value','watch_list_value','u_backout_plan_value','upon_reject_value','sys_updated_on_value','type_value','qualification_group_value','expected_end_value','approval_history_value','skills_value','number_value','u_access_areas_value','u_cancellation_reason_value','u_justification_value','u_copy_ci_to_task_value','previous_agent_value','state_value','u_is_aal_request_value','template_workflow_invoked_value','sys_created_by_value','knowledge_value','order_value','u_change_required_value','delivery_plan_value','cmdb_ci_value','impact_value','contract_value','active_value','work_notes_list_value','u_resolved_at_value','record_table_value','priority_value','sys_domain_path_value','sla_suspended_value','rejection_goto_value','u_racks_to_energise_value','maintenance_schedule_value','group_list_value','business_duration_value','u_resource_booking_value','approval_set_value','wf_activity_value','universal_request_value','template_value','short_description_value','correlation_display_value','delivery_task_value','work_start_value','request_type_value','additional_assignee_list_value','assigned_vendor_value','service_offering_value','sys_class_name_value','follow_up_value','closed_by_value','sla_suspended_on_value','u_risk_and_impact_analysis_value','vendor_reference_value','estimated_end_value','reschedule_maintenance_if_canceled_value','reassignment_count_value','assigned_to_value','request_category_value','requested_due_by_value','variables_value','sla_suspended_for_value','u_site_access_request_value','sla_due_value','opened_for_value','comments_and_work_notes_value','u_record_url_value','u_model_id_value','u_implementation_plan_value','substate_value','escalation_value','upon_approval_value','u_critical_value','correlation_id_value','spam_value','asset_value','made_sla_value','is_catalog_value','u_tolerance_end_value','task_effective_number_value','sys_updated_by_value','user_input_value','opened_by_value','sys_created_on_value','sys_domain_value','u_aal_email_value','maintenance_plan_value','details_value','route_reason_value','u_sla_notification_group_value','u_access_request_required_value','closed_at_value','business_service_value','time_worked_value','expected_start_value','opened_at_value','task_created_value','u_make_safe_value','work_end_value','u_access_request_type_value','u_maintenance_task_value','fulfillment_instructions_value','subcategory_value','work_notes_value','u_sub_subcategory_value','u_tolerance_start_value','u_is_access_request_value','initiated_from_value','assignment_group_value','description_value','calendar_duration_value','u_source_value','close_notes_value','contact_type_value','urgency_value','secure_notes_value','u_mop_value','company_value','department_value','activity_due_value','u_affected_customers_value','comments_value','approval_value','due_date_value','sys_mod_count_value','sys_tags_value','u_linked_mop_value','u_access_request_value','billable_value','u_expected_start_value','record_id_value','caller_value','location_value','category_value','user_value'],
          post_hook =[ delete_processed('servicenow_actual_facilities_request_lnd')],
          tags=['servicenow']
        )
    }}
SELECT *
FROM (
    SELECT
    ROW_NUMBER() OVER (PARTITION BY sys_id_value ORDER BY Load_dt DESC) AS row_num,
 CAST( sys_id_value AS varchar ( 50 )  ) AS sys_id_value ,
 CAST( parent_value AS varchar ( 50 )  ) AS parent_value ,
 CAST( sla_suspended_reason_value AS varchar ( 30 )  ) AS sla_suspended_reason_value ,
 CAST( watch_list_value AS varchar ( 500 )  ) AS watch_list_value ,
 CAST( u_backout_plan_value AS varchar ( 1000 )  ) AS u_backout_plan_value ,
 CAST( upon_reject_value AS varchar ( 30 )  ) AS upon_reject_value ,
 {{ convert_timezone('sys_updated_on_value') }} AS sys_updated_on_value ,
 CAST( type_value AS varchar ( 50 )  ) AS type_value ,
 CAST( qualification_group_value AS varchar ( 30 )  ) AS qualification_group_value ,
{{ convert_timezone('expected_end_value') }} AS expected_end_value ,
 CAST( approval_history_value AS varchar ( 30 )  ) AS approval_history_value ,
 CAST( skills_value AS varchar ( 30 )  ) AS skills_value ,
 CAST( number_value AS varchar ( 30 )  ) AS number_value ,
 CAST( u_access_areas_value AS varchar ( 4000 )  ) AS u_access_areas_value ,
 CAST( u_cancellation_reason_value AS varchar ( 100 )  ) AS u_cancellation_reason_value ,
 CAST( u_justification_value AS varchar ( 2000 )  ) AS u_justification_value ,
 CAST( u_copy_ci_to_task_value AS bit  ) AS u_copy_ci_to_task_value ,
 CAST( previous_agent_value AS varchar ( 50 )  ) AS previous_agent_value ,
 CAST( state_value AS int  ) AS state_value ,
 CAST( u_is_aal_request_value AS bit  ) AS u_is_aal_request_value ,
 CAST( template_workflow_invoked_value AS bit  ) AS template_workflow_invoked_value ,
 CAST( sys_created_by_value AS varchar ( 50 )  ) AS sys_created_by_value ,
 CAST( knowledge_value AS bit  ) AS knowledge_value ,
 CAST( order_value AS float  ) AS order_value ,
 CAST( u_change_required_value AS bit  ) AS u_change_required_value ,
 CAST( delivery_plan_value AS varchar ( 30 )  ) AS delivery_plan_value ,
 CAST( cmdb_ci_value AS varchar ( 50 )  ) AS cmdb_ci_value ,
 CAST( impact_value AS int  ) AS impact_value ,
 CAST( contract_value AS varchar ( 50 )  ) AS contract_value ,
 CAST( active_value AS bit  ) AS active_value ,
 CAST( work_notes_list_value AS varchar ( 50 )  ) AS work_notes_list_value ,
 {{ convert_timezone('u_resolved_at_value') }} AS u_resolved_at_value ,
 CAST( record_table_value AS varchar ( 50 )  ) AS record_table_value ,
 CAST( priority_value AS float  ) AS priority_value ,
 CAST( sys_domain_path_value AS varchar ( 5 )  ) AS sys_domain_path_value ,
 CAST( sla_suspended_value AS bit  ) AS sla_suspended_value ,
 CAST( rejection_goto_value AS varchar ( 100 )  ) AS rejection_goto_value ,
 CAST( u_racks_to_energise_value AS varchar ( 4000 )  ) AS u_racks_to_energise_value ,
 CAST( maintenance_schedule_value AS varchar ( 100 )  ) AS maintenance_schedule_value ,
 CAST( group_list_value AS varchar ( 30 )  ) AS group_list_value ,
 {{ convert_timezone('business_duration_value') }} AS business_duration_value ,
 CAST( u_resource_booking_value AS bit  ) AS u_resource_booking_value ,
 {{ convert_timezone('approval_set_value') }} AS approval_set_value ,
 CAST( wf_activity_value AS varchar ( 50 )  ) AS wf_activity_value ,
 CAST( universal_request_value AS varchar ( 30 )  ) AS universal_request_value ,
 CAST( template_value AS varchar ( 50 )  ) AS template_value ,
 CAST( short_description_value AS varchar ( 500 )  ) AS short_description_value ,
 CAST( correlation_display_value AS varchar ( 30 )  ) AS correlation_display_value ,
 CAST( delivery_task_value AS varchar ( 100 )  ) AS delivery_task_value ,
 {{ convert_timezone('work_start_value') }} AS work_start_value ,
 CAST( request_type_value AS varchar ( 100 )  ) AS request_type_value ,
 CAST( additional_assignee_list_value AS varchar ( 30 )  ) AS additional_assignee_list_value ,
 CAST( assigned_vendor_value AS varchar ( 30 )  ) AS assigned_vendor_value ,
 CAST( service_offering_value AS varchar (30 )  ) AS service_offering_value ,
 CAST( sys_class_name_value AS varchar ( 50 )  ) AS sys_class_name_value ,
 {{ convert_timezone('follow_up_value') }} AS follow_up_value ,
 CAST( closed_by_value AS varchar ( 50 )  ) AS closed_by_value ,
 {{ convert_timezone('sla_suspended_on_value') }} AS sla_suspended_on_value ,
 CAST( u_risk_and_impact_analysis_value AS varchar ( 4000 )  ) AS u_risk_and_impact_analysis_value ,
 CAST( vendor_reference_value AS varchar ( 50 )  ) AS vendor_reference_value ,
 {{ convert_timezone('estimated_end_value') }} AS estimated_end_value ,
 CAST( reschedule_maintenance_if_canceled_value AS bit  ) AS reschedule_maintenance_if_canceled_value ,
 CAST( reassignment_count_value AS int  ) AS reassignment_count_value ,
 CAST( assigned_to_value AS varchar ( 50 )  ) AS assigned_to_value ,
 CAST( request_category_value AS varchar ( 30 )  ) AS request_category_value ,
 {{ convert_timezone('requested_due_by_value') }} AS requested_due_by_value ,
 CAST( variables_value AS varchar ( 50 )  ) AS variables_value ,
 CAST( sla_suspended_for_value AS varchar ( 30 )  ) AS sla_suspended_for_value ,
 CAST( u_site_access_request_value AS varchar ( 50 )  ) AS u_site_access_request_value ,
 {{ convert_timezone('sla_due_value') }} AS sla_due_value ,
 CAST( opened_for_value AS varchar ( 50 )  ) AS opened_for_value ,
 CAST( comments_and_work_notes_value AS varchar ( 30 )  ) AS comments_and_work_notes_value ,
 CAST( u_record_url_value AS varchar ( 200 )  ) AS u_record_url_value ,
 CAST( u_model_id_value AS varchar ( 50 )  ) AS u_model_id_value ,
 CAST( u_implementation_plan_value AS varchar ( MAX )  ) AS u_implementation_plan_value ,
 CAST( substate_value AS float  ) AS substate_value ,
 CAST( escalation_value AS int  ) AS escalation_value ,
 CAST( upon_approval_value AS varchar ( 50 )  ) AS upon_approval_value ,
 CAST( u_critical_value AS bit  ) AS u_critical_value ,
 CAST( correlation_id_value AS varchar ( 30 )  ) AS correlation_id_value ,
 CAST( spam_value AS bit  ) AS spam_value ,
 CAST( asset_value AS varchar ( 30 )  ) AS asset_value ,
 CAST( made_sla_value AS bit  ) AS made_sla_value ,
 CAST( is_catalog_value AS bit  ) AS is_catalog_value ,
 {{ convert_timezone('u_tolerance_end_value') }} AS u_tolerance_end_value ,
 CAST( task_effective_number_value AS varchar ( 50 )  ) AS task_effective_number_value ,
 CAST( sys_updated_by_value AS varchar ( 50 )  ) AS sys_updated_by_value ,
 CAST( user_input_value AS varchar ( 30 )  ) AS user_input_value ,
 CAST( opened_by_value AS varchar ( 50 )  ) AS opened_by_value ,
 {{ convert_timezone('sys_created_on_value') }} AS sys_created_on_value ,
 CAST( sys_domain_value AS varchar ( 50 )  ) AS sys_domain_value ,
 CAST( u_aal_email_value AS varchar ( 100 )  ) AS u_aal_email_value ,
 CAST( maintenance_plan_value AS varchar ( 50 )  ) AS maintenance_plan_value ,
 CAST( details_value AS varchar ( 4000 )  ) AS details_value ,
 CAST( route_reason_value AS float  ) AS route_reason_value ,
 CAST( u_sla_notification_group_value AS varchar ( 100 )  ) AS u_sla_notification_group_value ,
 CAST( u_access_request_required_value AS bit  ) AS u_access_request_required_value ,
 {{ convert_timezone('closed_at_value') }} AS closed_at_value ,
 CAST( business_service_value AS varchar ( 50 )  ) AS business_service_value ,
 CAST( time_worked_value AS varchar ( 50 )  ) AS time_worked_value ,
 {{ convert_timezone('expected_start_value') }} AS expected_start_value ,
 {{ convert_timezone('opened_at_value') }} AS opened_at_value ,
 CAST( task_created_value AS bit  ) AS task_created_value ,
 CAST( u_make_safe_value AS bit  ) AS u_make_safe_value ,
 {{ convert_timezone('work_end_value') }} AS work_end_value ,
 CAST( u_access_request_type_value AS varchar ( 50 )  ) AS u_access_request_type_value ,
 CAST( u_maintenance_task_value AS varchar ( 50 )  ) AS u_maintenance_task_value ,
 CAST( fulfillment_instructions_value AS varchar ( 30 )  ) AS fulfillment_instructions_value ,
 CAST( subcategory_value AS varchar ( 50 )  ) AS subcategory_value ,
 CAST( work_notes_value AS varchar ( 30 )  ) AS work_notes_value ,
 CAST( u_sub_subcategory_value AS varchar ( 100 )  ) AS u_sub_subcategory_value ,
 {{ convert_timezone('u_tolerance_start_value') }} AS u_tolerance_start_value ,
 CAST( u_is_access_request_value AS bit  ) AS u_is_access_request_value ,
 CAST( initiated_from_value AS varchar ( 50 )  ) AS initiated_from_value ,
 CAST( assignment_group_value AS varchar ( 50 )  ) AS assignment_group_value ,
 CAST( description_value AS varchar ( MAX )  ) AS description_value ,
 {{ convert_timezone('calendar_duration_value') }} AS calendar_duration_value ,
 CAST( u_source_value AS varchar ( 30 )  ) AS u_source_value ,
 CAST( close_notes_value AS varchar ( 30 )  ) AS close_notes_value ,
 CAST( contact_type_value AS varchar ( 30 )  ) AS contact_type_value ,
 CAST( urgency_value AS int  ) AS urgency_value ,
 CAST( secure_notes_value AS varchar ( 100 )  ) AS secure_notes_value ,
 CAST( u_mop_value AS varchar ( 4000 )  ) AS u_mop_value ,
 CAST( company_value AS varchar ( 100 )  ) AS company_value ,
 CAST( department_value AS varchar ( 50 )  ) AS department_value ,
 {{ convert_timezone('activity_due_value') }} AS activity_due_value ,
 CAST( u_affected_customers_value AS varchar ( 50 )  ) AS u_affected_customers_value ,
 CAST( comments_value AS varchar ( 100 )  ) AS comments_value ,
 CAST( approval_value AS varchar ( 50 )  ) AS approval_value ,
 {{ convert_timezone('due_date_value') }} AS due_date_value ,
 CAST( sys_mod_count_value AS int  ) AS sys_mod_count_value ,
 CAST( sys_tags_value AS varchar ( 50 )  ) AS sys_tags_value ,
 CAST( u_linked_mop_value AS varchar ( MAX )  ) AS u_linked_mop_value ,
 CAST( u_access_request_value AS varchar ( 50 )  ) AS u_access_request_value ,
 CAST( billable_value AS bit  ) AS billable_value ,
 {{ convert_timezone('u_expected_start_value') }} AS u_expected_start_value ,
 CAST( record_id_value AS varchar ( 100 )  ) AS record_id_value ,
 CAST( caller_value AS varchar ( 100 )  ) AS caller_value ,
 CAST( location_value AS varchar ( 100 )  ) AS location_value ,
 CAST( category_value AS varchar ( 100 )  ) AS category_value ,
 CAST( user_value AS varchar ( 50 )  ) AS user_value ,
 Source_File ,
 {{ convert_timezone('Load_dt') }} AS Load_dt 
 FROM
    {{ source('staging','servicenow_actual_facilities_request_lnd') }}
​
)AS Subquery
WHERE row_num = 1;
{% endsnapshot %}   