{% snapshot servicenow_actual_change_request_stg %}
    {{
        config(
          target_schema='staging',
          strategy='check',
          unique_key='sys_id_value',
          check_cols=['delivery_plan_value','short_description_value','delivery_task_value','change_plan_value','business_service_value','description_value','time_worked_value','made_sla_value','number_value','close_notes_value','watch_list_value','backout_plan_value','comments_value','requested_by_date_value','assigned_to_value','approval_history_value','production_system_value','parent_value','sys_created_by_value','sys_updated_on_value','risk_value','reason_value','correlation_id_value','category_value','activity_due_value','work_notes_list_value','cmdb_ci_value','correlation_display_value','business_duration_value','opened_by_value','test_plan_value','knowledge_value','order_value','sla_due_value','requested_by_value','cab_recommendation_value','type_value','comments_and_work_notes_value','justification_value','review_date_value','sys_domain_value','group_list_value','closed_by_value','location_value','work_start_value','calendar_duration_value','approval_set_value','work_end_value','sys_created_on_value','phase_value','cab_date_value','sys_class_name_value','additional_assignee_list_value','conflict_status_value','upon_approval_value','follow_up_value','company_value','active_value','sys_domain_path_value','work_notes_value','sys_mod_count_value','escalation_value','closed_at_value','end_date_value','approval_value','user_input_value','upon_reject_value','impact_value','reassignment_count_value','phase_state_value','state_value','start_date_value','outside_maintenance_schedule_value','sys_tags_value','scope_value','priority_value','expected_start_value','contact_type_value','sys_updated_by_value','urgency_value','due_date_value','assignment_group_value','opened_at_value','review_status_value','conflict_last_run_value','review_comments_value','implementation_plan_value','skills_value','cab_delegate_value','u_airtrunk_managment_approval_value','contract_value','rejection_goto_value','wf_activity_value','universal_request_value','std_change_producer_version_value','service_offering_value','variables_value','u_record_url_value','u_sub_category_value','u_probability_value','task_effective_number_value','on_hold_task_value','u_facilities_request_value','route_reason_value','u_sub_sub_category_value','chg_model_value','close_code_value','on_hold_reason_value','cab_required_value','u_mop_value','u_affected_customers_value','on_hold_value','u_linked_mop_value','u_construction_project_value','cab_date_time_value','unauthorized_value','risk_impact_analysis_value'],
          post_hook =[ delete_processed('servicenow_actual_change_request_lnd')],
		  tags=['servicenow']
        )
    }}
SELECT *
FROM (
    SELECT
    ROW_NUMBER() OVER (PARTITION BY sys_id_value ORDER BY Load_dt DESC) AS row_num,
    CAST( delivery_plan_value AS varchar ( 30 )  ) AS delivery_plan_value ,
    CAST( short_description_value AS varchar ( 200 )  ) AS short_description_value ,
    CAST( delivery_task_value AS varchar ( 30 )  ) AS delivery_task_value ,
    CAST( change_plan_value AS varchar ( 30 )  ) AS change_plan_value ,
    CAST( business_service_value AS varchar ( 30 )  ) AS business_service_value ,
    CAST( description_value AS varchar ( MAX )  ) AS description_value ,
    CAST( time_worked_value AS varchar ( 30 )  ) AS time_worked_value ,
    CAST( made_sla_value AS bit  ) AS made_sla_value ,
    CAST( number_value AS varchar ( 20 )  ) AS number_value ,
    CAST( close_notes_value AS varchar ( MAX )  ) AS close_notes_value ,
    CAST( watch_list_value AS varchar ( 300 )  ) AS watch_list_value ,
    CAST( backout_plan_value AS varchar ( MAX )  ) AS backout_plan_value ,
    CAST( comments_value AS varchar ( 30 )  ) AS comments_value ,
    {{ convert_timezone('requested_by_date_value') }} AS requested_by_date_value ,
    CAST( assigned_to_value AS varchar ( 50 )  ) AS assigned_to_value ,
    CAST( approval_history_value AS varchar ( 30 )  ) AS approval_history_value ,
    CAST( production_system_value AS bit  ) AS production_system_value ,
    CAST( parent_value AS varchar ( 50 )  ) AS parent_value ,
    CAST( sys_created_by_value AS varchar ( 50 )  ) AS sys_created_by_value ,
    {{ convert_timezone('sys_updated_on_value') }} AS sys_updated_on_value ,
    CAST( risk_value AS int  ) AS risk_value ,
    CAST( reason_value AS varchar ( 30 )  ) AS reason_value ,
    CAST( correlation_id_value AS varchar ( 30 )  ) AS correlation_id_value ,
    CAST( category_value AS varchar ( 100 )  ) AS category_value ,
    {{ convert_timezone('activity_due_value') }} AS activity_due_value ,
    CAST( work_notes_list_value AS varchar ( 200 )  ) AS work_notes_list_value ,
    CAST( cmdb_ci_value AS varchar ( 50 )  ) AS cmdb_ci_value ,
    CAST( sys_id_value AS varchar ( 50 )  ) AS sys_id_value ,
    CAST( correlation_display_value AS varchar ( 30 )  ) AS correlation_display_value ,
    {{ convert_timezone('business_duration_value') }} AS business_duration_value ,
    CAST( opened_by_value AS varchar ( 50 )  ) AS opened_by_value ,
    CAST( test_plan_value AS varchar ( MAX )  ) AS test_plan_value ,
    CAST( knowledge_value AS bit  ) AS knowledge_value ,
    CAST( order_value AS float  ) AS order_value ,
    {{ convert_timezone('sla_due_value') }} AS sla_due_value ,
    CAST( requested_by_value AS varchar ( 50 )  ) AS requested_by_value ,
    CAST( cab_recommendation_value AS varchar ( 300 )  ) AS cab_recommendation_value ,
    CAST( type_value AS varchar ( 20 )  ) AS type_value ,
    CAST( comments_and_work_notes_value AS varchar ( 30 )  ) AS comments_and_work_notes_value ,
    CAST( justification_value AS varchar ( MAX )  ) AS justification_value ,
    {{ convert_timezone('review_date_value') }} AS review_date_value ,
    CAST( sys_domain_value AS varchar ( 20 )  ) AS sys_domain_value ,
    CAST( group_list_value AS varchar ( 30 )  ) AS group_list_value ,
    CAST( closed_by_value AS varchar ( 50 )  ) AS closed_by_value ,
    CAST( location_value AS varchar ( 50 )  ) AS location_value ,
    {{ convert_timezone('work_start_value') }} AS work_start_value ,
    {{ convert_timezone('calendar_duration_value') }} AS calendar_duration_value ,
    {{ convert_timezone('approval_set_value') }} AS approval_set_value ,
    {{ convert_timezone('work_end_value') }} AS work_end_value ,
    {{ convert_timezone('sys_created_on_value') }} AS sys_created_on_value,
    CAST( phase_value AS varchar ( 20 )  ) AS phase_value ,
    {{ convert_timezone('cab_date_value') }} AS cab_date_value ,
    CAST( sys_class_name_value AS varchar ( 50 )  ) AS sys_class_name_value ,
    CAST( additional_assignee_list_value AS varchar ( 50 )  ) AS additional_assignee_list_value ,
    CAST( conflict_status_value AS varchar ( 30 )  ) AS conflict_status_value ,
    CAST( upon_approval_value AS varchar ( 20 )  ) AS upon_approval_value ,
    {{ convert_timezone('follow_up_value') }} AS follow_up_value ,
    CAST( company_value AS varchar ( 100 )  ) AS company_value ,
    CAST( active_value AS bit  ) AS active_value ,
    CAST( sys_domain_path_value AS varchar ( 10 )  ) AS sys_domain_path_value ,
    CAST( work_notes_value AS varchar ( 30 )  ) AS work_notes_value ,
    CAST( sys_mod_count_value AS int  ) AS sys_mod_count_value ,
    CAST( escalation_value AS int  ) AS escalation_value ,
    {{ convert_timezone('closed_at_value') }} AS closed_at_value ,
    {{ convert_timezone('end_date_value') }} AS end_date_value ,
    CAST( approval_value AS varchar ( 50 )  ) AS approval_value ,
    CAST( user_input_value AS varchar ( 30 )  ) AS user_input_value ,
    CAST( upon_reject_value AS varchar ( 30 )  ) AS upon_reject_value ,
    CAST( impact_value AS float  ) AS impact_value ,
    CAST( reassignment_count_value AS int  ) AS reassignment_count_value ,
    CAST( phase_state_value AS varchar ( 10 )  ) AS phase_state_value ,
    CAST( state_value AS int  ) AS state_value ,
    {{ convert_timezone('start_date_value') }} AS start_date_value ,
    CAST( outside_maintenance_schedule_value AS bit  ) AS outside_maintenance_schedule_value ,
    CAST( sys_tags_value AS varchar ( 30 )  ) AS sys_tags_value ,
    CAST( scope_value AS int  ) AS scope_value ,
    CAST( priority_value AS int  ) AS priority_value ,
    {{ convert_timezone('expected_start_value') }} AS expected_start_value ,
    CAST( contact_type_value AS varchar ( 30 )  ) AS contact_type_value ,
    CAST( sys_updated_by_value AS varchar ( 50 )  ) AS sys_updated_by_value ,
    CAST( urgency_value AS int  ) AS urgency_value ,
    {{ convert_timezone('due_date_value') }} AS due_date_value ,
    CAST( assignment_group_value AS varchar ( 100 )  ) AS assignment_group_value ,
    {{ convert_timezone('opened_at_value') }} AS opened_at_value ,
    CAST( review_status_value AS float  ) AS review_status_value ,
    {{ convert_timezone('conflict_last_run_value') }} AS conflict_last_run_value ,
    CAST( review_comments_value AS varchar ( 30 )  ) AS review_comments_value ,
    CAST( implementation_plan_value AS varchar ( MAX )  ) AS implementation_plan_value ,
    CAST( skills_value AS varchar ( 30 )  ) AS skills_value ,
    CAST( cab_delegate_value AS varchar ( 100 )  ) AS cab_delegate_value ,
    CAST( u_airtrunk_managment_approval_value AS varchar ( 100 )  ) AS u_airtrunk_managment_approval_value ,
    CAST( contract_value AS varchar ( 30 )  ) AS contract_value ,
    CAST( rejection_goto_value AS varchar ( 50 )  ) AS rejection_goto_value ,
    CAST( wf_activity_value AS varchar ( 50 )  ) AS wf_activity_value ,
    CAST( universal_request_value AS varchar ( 30 )  ) AS universal_request_value ,
    CAST( std_change_producer_version_value AS varchar ( 50 )  ) AS std_change_producer_version_value ,
    CAST( service_offering_value AS varchar ( 30 )  ) AS service_offering_value ,
    CAST( variables_value AS varchar ( 50 )  ) AS variables_value ,
    CAST( u_record_url_value AS varchar ( 300 )  ) AS u_record_url_value ,
    CAST( u_sub_category_value AS varchar ( 100 )  ) AS u_sub_category_value ,
    CAST( u_probability_value AS float  ) AS u_probability_value ,
    CAST( task_effective_number_value AS varchar ( 30 )  ) AS task_effective_number_value ,
    CAST( on_hold_task_value AS varchar ( 30 )  ) AS on_hold_task_value ,
    CAST( u_facilities_request_value AS varchar ( 100 )  ) AS u_facilities_request_value ,
    CAST( route_reason_value AS float  ) AS route_reason_value ,
    CAST( u_sub_sub_category_value AS varchar ( 100 )  ) AS u_sub_sub_category_value ,
    CAST( chg_model_value AS varchar (30 )  ) AS chg_model_value ,
    CAST( close_code_value AS varchar ( 50 )  ) AS close_code_value ,
    CAST( on_hold_reason_value AS varchar ( 2000 )  ) AS on_hold_reason_value ,
    CAST( cab_required_value AS bit  ) AS cab_required_value ,
    CAST( u_mop_value AS varchar ( 2000 )  ) AS u_mop_value ,
    CAST( u_affected_customers_value AS varchar ( 1000 )  ) AS u_affected_customers_value ,
    CAST( on_hold_value AS bit  ) AS on_hold_value ,
    CAST( u_linked_mop_value AS varchar ( MAX )  ) AS u_linked_mop_value ,
    CAST( u_construction_project_value AS bit  ) AS u_construction_project_value ,
    {{ convert_timezone('cab_date_time_value') }} AS cab_date_time_value ,
    CAST( unauthorized_value AS bit  ) AS unauthorized_value ,
    CAST( risk_impact_analysis_value AS varchar ( MAX )  ) AS risk_impact_analysis_value ,
    Source_File ,
    {{ convert_timezone('Load_dt') }} AS Load_dt
 FROM 
   {{ source('staging','servicenow_actual_change_request_lnd') }}
)AS Subquery
WHERE row_num = 1;
{% endsnapshot %}